nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.4.1.cjs
npmScopes:
  rps:
    npmPublishRegistry: "https://npmjs.rpso.in"
    npmRegistryServer: "https://npmjs.rpso.in"
    npmAlwaysAuth: false