# This is a basic workflow to help you get started with Actions

name: Feature Building Test
# Controls when the workflow will run
on:
  push:
    branches:
      - 'feat/**'
      - 'feature/**'
      - 'fix/**'
      - bugfix/*
      - hotfix/**
      - release/**
      
jobs:
  lint-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        target:
          - lint
          - test

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-shas
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Yarn Affected ${{ matrix.target }}
        run: yarn nx affected --target=${TARGET} --base=${{ steps.set-shas.outputs.base }} --head=${{ steps.set-shas.outputs.head }}
        env:
          TARGET: ${{ matrix.target }}

  build-pack:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        target:
          - build
          - pack

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: set-shas
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Yarn Affected ${{ matrix.target }}
        run: yarn nx affected --target=${TARGET} --base=${{ steps.set-shas.outputs.base }} --head=${{ steps.set-shas.outputs.head }}
        env:
          TARGET: ${{ matrix.target }}
